r-dbi/RSQLite

R/table.R
in dbReadTable(), dbRemoveTable(), and dbListFields(). Fixes #106.
Fixes hadley/dplyr#926.
=> Quote table name

docs/articles/RSQLite.html, docs/reference/rsqliteVersion.html, src/vendor/sqlite3/sqlite3.h, src/vendor/sqlite3/sqlite3ext.h
=> Update sqlite3 to 3.22

src/vendor/sqlite3/sqlite3.h, src/vendor/sqlite3/sqlite3ext.h
=> Upgrade to sqlite 3.25.3

README.md
Looks like it was pointing to a previous org
=> Fixed Travis badge

src/vendor/sqlite3/sqlite3.h, src/vendor/sqlite3/sqlite3ext.h
so we can have window functions woo!
=> Updated bundled sqlite sources to 3.28.0

data-raw/regexp.patch, data-raw/upgrade.R, src/vendor/sqlite3/regexp.c, src/vendor/sqlite3/sqlite3.h, src/vendor/sqlite3/sqlite3ext.h
=> Upgrade to SQLite 3.33.0

R/table.R, man/SQLiteConnection-class.Rd
=> Use transaction for dbAppendTable()

DESCRIPTION, NEWS.md, R/connect.R, R/copy.R, R/extensions.R, README.Rmd, README.md, cran-comments.md, inst/WORDLIST, man/SQLite.Rd, man/initExtension.Rd, man/sqliteCopyDatabase.Rd, vignettes/RSQLite.Rmd
=> CRAN release v2.2.1

.Rbuildignore, NEWS.md, cran-comments.md
=> CRAN release v2.2.2

NEWS.md, README.Rmd, README.md, cran-comments.md
=> CRAN release v2.2.3

NEWS.md, cran-comments.md
=> CRAN release v2.2.4

NEWS.md, _pkgdown.yml, cran-comments.md
=> CRAN release v2.2.5

NEWS.md, cran-comments.md
=> CRAN release v2.2.6

src/DbConnection.h
=> remove duplicate semi-colon

NEWS.md, cran-comments.md
=> CRAN release v2.2.7

.github/workflows/R-CMD-check.yaml
=> Fix builds on Xenial

src/vendor/boost/detail/fenv.hpp
Restore missing file following instructions in #362.
Closes #367.
=> Fix build on Centos

NEWS.md, cran-comments.md
=> CRAN release v2.2.8

tests/testthat/helper-DBItest.R
=> Adapt to DBItest 1.7.2

R/transactions.R, tests/testthat/test-transactions.R
=> Support keywords in savepoint names

NEWS.md, cran-comments.md
=> CRAN release v2.2.9

DESCRIPTION
=> Enable auto-styling

NEWS.md, README.Rmd, README.md, cran-comments.md
=> CRAN release v2.2.11

src/DbColumnStorage.h
comparing with
https://github.com/r-dbi/RSQLite/blob/402e0093c71efc8940fc942491c0b4430c89d518/src/DbColumnStorage.cpp#L155
=> sync parameters between header/source

.github/workflows/custom/before-install/action.yml
=> Avoid checking package sizes on GitHub Actions

NEWS.md, cran-comments.md
=> CRAN release v2.2.13

NEWS.md, cran-comments.md, src/vendor/sqlite3/sqlite3.h
=> CRAN release v2.2.14

NEWS.md, cran-comments.md
=> CRAN release v2.2.15

DESCRIPTION, NEWS.md, cran-comments.md
=> CRAN release v2.2.16

NEWS.md, cran-comments.md
=> CRAN release v2.2.17

NEWS.md, cran-comments.md
=> CRAN release v2.2.18

DESCRIPTION, tests/testthat.R, tests/testthat/test-affinity.R, tests/testthat/test-astyle.R, tests/testthat/test-basic-types.R, tests/testthat/test-blob.R, tests/testthat/test-column-info.R, tests/testthat/test-data-type.R, tests/testthat/test-dbClearResult.R, tests/testthat/test-dbConnect.R, tests/testthat/test-dbSendQuery.R, tests/testthat/test-dbWriteTable.R, tests/testthat/test-dbWriteTableAutoincrement.R, tests/testthat/test-encoding.R, tests/testthat/test-error.R, tests/testthat/test-exception.R, tests/testthat/test-extendedTypes.R, tests/testthat/test-json.R, tests/testthat/test-readonly.R, tests/testthat/test-regularExpressions.R, tests/testthat/test-sd.R, tests/testthat/test-sqliteCopyDatabase.R, tests/testthat/test-sqliteQuickColumn.R, tests/testthat/test-transactions.R
=> feat: Use testthat edition 3

NEWS.md, cran-comments.md, src/vendor/boost/lexical_cast/detail/converter_lexical_streams.hpp, tests/testthat/test-encoding.R
=> CRAN release v2.2.19

.Rbuildignore, .github/workflows/commit/action.yml, .github/workflows/dep-matrix/action.yml, .github/workflows/get-extra/action.yml, .github/workflows/revdep.yaml, .github/workflows/style/action.yml, .github/workflows/update-snapshots/action.yml, NEWS.md, cran-comments.md
=> CRAN release v2.2.20

NEWS.md, cran-comments.md, src/Makevars, src/RSQLite.h
=> CRAN release v2.3.0

NEWS.md, cran-comments.md, src/vendor/boost/container/stable_vector.hpp
=> CRAN release v2.3.1

DESCRIPTION, NEWS.md, R/dbConnect_SQLiteDriver.R, README.Rmd, README.md, cran-comments.md, man/SQLite.Rd, src/vendor/extensions/regexp.c, src/vendor/extensions/series.c, src/vendor/sqlite3/sqlite3.h
=> CRAN release v2.3.2

DESCRIPTION, NEWS.md, README.md, cran-comments.md
{{{ crp_changes }}}
{{{ check_cran_comments }}}
- Run `fledge::release()`{{{ fledge_gha_workflow_release }}}
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()`{{{ fledge_gha_workflow_release }}}
=> CRAN release v2.3.5

DESCRIPTION, NEWS.md, cran-comments.md
- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)
=> CRAN release v2.3.6

DESCRIPTION, NEWS.md, cran-comments.md
- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)
=> CRAN release v2.3.7

src/SqliteResultImpl.h
=> fledge: Bump version to 2.4.3.9004 (#627)
